name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Deno
      run: |
        curl -L https://deno.land/x/install/install.sh | sh -s "v0.25.0"
        export PATH="$HOME/.deno/bin:$PATH"
    - name: Run the tests
      run: |
        /home/runner/.local/bin/deno run -A test.ts




